import { z } from 'zod';

/**
 * All API configuration comes from the environment. The public README's
 * configuration table is generated from the descriptions here, so every
 * setting a self-hoster can touch must be described in plain words.
 */
const schema = z.object({
  HOST: z.string().default('0.0.0.0'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),

  DATABASE_URL: z.string().min(1).describe('Connection string for the application role.'),
  DATABASE_ADMIN_URL: z
    .string()
    .min(1)
    .optional()
    .describe('Connection string for the migration (table-owning) role. Defaults to DATABASE_URL.'),
  FDV_RUN_MIGRATIONS: z
    .enum(['true', 'false'])
    .default('true')
    .describe('Apply pending database migrations on start.'),

  FDV_MASTER_KEY: z
    .string()
    .min(32, 'must be at least 32 characters; generate it with scripts/gen-env.mjs')
    .optional()
    .describe('Wraps every other key. Back it up off the server.'),
  FDV_MASTER_KEY_FILE: z
    .string()
    .min(1)
    .optional()
    .describe('Path to a file holding the master key instead of FDV_MASTER_KEY.'),

  FDV_LOCAL_VAULT_DIR: z
    .string()
    .min(1)
    .default('/data/vault')
    .describe('Folder for the built-in local vault. A Docker volume by default.'),

  FDV_VAPID_PUBLIC_KEY: z
    .string()
    .min(1)
    .optional()
    .describe('Public half of the Web Push signing key. Generated by scripts/gen-env.mjs.'),

  FDV_DISPLAY_NAME: z.string().min(1).default('Our family vault'),
  FDV_EDITION: z.enum(['self_hosted', 'hosted']).default('self_hosted'),
  FDV_MAX_UPLOAD_BYTES: z.coerce
    .number()
    .int()
    .positive()
    .default(100 * 1024 * 1024)
    .describe('Largest single file the vault accepts.'),

  FDV_BASE_URL: z
    .string()
    .url()
    .default('http://localhost:8080')
    .describe(
      'Where the vault is published. Reminder emails link to it, and ' +
        'passkeys are bound to its hostname.',
    ),

  FDV_SMTP_URL: z
    .string()
    .regex(/^smtps?:[/][/]/, 'Use smtp://… or smtps://…')
    .optional()
    .describe(
      'A mail server for messages that prove who somebody is — password-reset ' +
        'links. Set by whoever runs the server, because a mail server set in ' +
        'the app is one an owner can point anywhere, and a reset link read ' +
        'by somebody else is a way into that person\u2019s private documents.',
    ),

  FDV_RP_ID: z
    .string()
    .min(1)
    .optional()
    .describe(
      'The domain passkeys belong to. Defaults to the hostname of ' +
        'FDV_BASE_URL, which is right unless the vault is served from a ' +
        'subdomain of a name you want the passkeys to work across.',
    ),

  FDV_TRUST_PROXY: z
    .enum(['private', 'all', 'none'])
    .default('private')
    .describe(
      'Whose X-Forwarded-For to believe. "private" trusts the container ' +
        'network and any reverse proxy on a private address, which is the ' +
        'compose setup; "all" is for a proxy elsewhere; "none" records the ' +
        'connecting address as it is.',
    ),
});

export type ApiConfig = z.infer<typeof schema>;

const withMasterKey = schema.refine((c) => c.FDV_MASTER_KEY || c.FDV_MASTER_KEY_FILE, {
  message: 'set FDV_MASTER_KEY (or FDV_MASTER_KEY_FILE); generate it with scripts/gen-env.mjs',
  path: ['FDV_MASTER_KEY'],
});

/**
 * An environment variable set to nothing is not set.
 *
 * Compose writes `FDV_RP_ID: ${FDV_RP_ID:-}` for anything optional, which
 * hands the container an empty string rather than leaving the variable
 * out. Without this, every optional setting would have to tolerate `''`
 * on its own, and the one that forgot would fail at startup with a
 * message about a field the self-hoster never set.
 */
function present(env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  return Object.fromEntries(Object.entries(env).filter(([, v]) => v !== ''));
}

export function loadConfig(env: NodeJS.ProcessEnv = process.env): ApiConfig {
  const parsed = withMasterKey.safeParse(present(env));
  if (!parsed.success) {
    const problems = parsed.error.issues
      .map((i) => `  ${i.path.join('.') || '(root)'}: ${i.message}`)
      .join('\n');
    throw new Error(`invalid configuration:\n${problems}`);
  }
  return parsed.data;
}
