import { z } from 'zod';

/** A URL, or null when it is not one. */
function parsedUrl(value: string): URL | null {
  try {
    return new URL(value);
  } catch {
    return null;
  }
}

/**
 * All API configuration comes from the environment. The public README's
 * configuration table is generated from the descriptions here, so every
 * setting a self-hoster can touch must be described in plain words.
 */
const schema = z.object({
  HOST: z.string().default('0.0.0.0'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3000),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace']).default('info'),

  DATABASE_URL: z.string().min(1).describe('Connection string for the application role.'),
  DATABASE_ADMIN_URL: z
    .string()
    .min(1)
    .optional()
    .describe('Connection string for the migration (table-owning) role. Defaults to DATABASE_URL.'),
  FDV_RUN_MIGRATIONS: z
    .enum(['true', 'false'])
    .default('true')
    .describe('Apply pending database migrations on start.'),

  FDV_MASTER_KEY: z
    .string()
    .min(32, 'must be at least 32 characters; generate it with scripts/gen-env.mjs')
    .optional()
    .describe('Wraps every other key. Back it up off the server.'),
  FDV_MASTER_KEY_FILE: z
    .string()
    .min(1)
    .optional()
    .describe('Path to a file holding the master key instead of FDV_MASTER_KEY.'),

  FDV_LOCAL_VAULT_DIR: z
    .string()
    .min(1)
    .default('/data/vault')
    .describe('Folder for the built-in local vault. A Docker volume by default.'),

  FDV_VAPID_PUBLIC_KEY: z
    .string()
    .min(1)
    .optional()
    .describe('Public half of the Web Push signing key. Generated by scripts/gen-env.mjs.'),

  FDV_PUSH_ALLOW_PRIVATE_ENDPOINTS: z
    .enum(['true', 'false'])
    .default('false')
    .describe(
      'Accept push addresses inside your own network — a UnifiedPush distributor (ntfy) ' +
        'on the LAN. The worker has the same setting and checks again when it sends.',
    ),

  FDV_DISPLAY_NAME: z.string().min(1).default('Our family vault'),
  FDV_EDITION: z.enum(['self_hosted', 'hosted']).default('self_hosted'),
  FDV_MAX_UPLOAD_BYTES: z.coerce
    .number()
    .int()
    .positive()
    .default(100 * 1024 * 1024)
    .describe('Largest single file the vault accepts.'),
  FDV_RATE_LIMIT_PER_MINUTE: z.coerce
    .number()
    .int()
    .min(60)
    .max(100_000)
    .default(300)
    .describe(
      'How many requests one address may make in a minute, beyond the tighter limits on ' +
        'signing in and opening links. Raise it when many devices share one address.',
    ),
  FDV_SHARE_MAX_DAYS: z.coerce
    .number()
    .int()
    .min(1)
    .max(90)
    .default(90)
    .describe(
      'The longest a share link may last, in days (1 to 90). A link always ends: ' +
        'this only shortens the longest end the vault accepts.',
    ),
  FDV_OFFLINE_MAX_DAYS: z.coerce
    .number()
    .int()
    .min(1)
    .max(365)
    .default(90)
    .describe(
      'How many days a phone may show the Essentials it keeps without reaching the ' +
        'vault. After that it hides them until it has checked in again.',
    ),

  FDV_BASE_URL: z
    .string()
    .url()
    .default('http://localhost:8080')
    .describe(
      'Where the vault is published. Reminder emails link to it, and ' +
        'passkeys are bound to its hostname.',
    ),

  FDV_PUBLIC_URL: z
    .string()
    .url()
    .superRefine((value, ctx) => {
      const url = parsedUrl(value);
      if (!url) return; // .url() has said so
      // A browser keeps the cookie Open gives only on a secure page, so over
      // plain http a link is counted as opened and its file never comes.
      // Browsers count this computer as secure, so http://localhost is fine.
      const local = ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname);
      if (!(url.protocol === 'https:' || (url.protocol === 'http:' && local))) {
        ctx.addIssue({
          code: 'custom',
          message:
            'Use https://… — over plain http a share link cannot deliver its document (http:// is only for localhost)',
        });
        return;
      }
      // A link is this followed by /s#…: a path, a query or a fragment would
      // put it somewhere else, and a name and password before an @ are not
      // the host they look like (https://localhost@evil.com is evil.com).
      if (url.username || url.password || url.pathname !== '/' || url.search || url.hash) {
        ctx.addIssue({
          code: 'custom',
          message: 'Give the address alone: https://share.example.com',
        });
      }
    })
    // Kept as the browser would write it: scheme and host in lower case,
    // no default port and no slash at the end.
    .transform((value) => parsedUrl(value)?.origin ?? value)
    .optional()
    .describe(
      'The public-only site (docker/caddy/Caddyfile.public-only), when there is ' +
        'one: the address the share links the vault makes start with, so the ' +
        'people they are sent to can reach them. It must be https://, and the ' +
        'address alone, with no path after it. Unset, a ' +
        'link starts with the address it was made at.',
    ),

  FDV_SMTP_URL: z
    .string()
    .regex(/^smtps?:[/][/]/, 'Use smtp://… or smtps://…')
    .optional()
    .describe(
      'A mail server for messages that prove who somebody is — password-reset ' +
        'links, and the codes a share link can ask for (5.20). Set by whoever ' +
        'runs the server, because a mail server set in the app is one an ' +
        'owner can point anywhere, and a reset link or a code read ' +
        'by somebody else is a way into that person\u2019s private documents.',
    ),

  FDV_RP_ID: z
    .string()
    .min(1)
    .optional()
    .describe(
      'The domain passkeys belong to. Defaults to the hostname of ' +
        'FDV_BASE_URL, which is right unless the vault is served from a ' +
        'subdomain of a name you want the passkeys to work across.',
    ),

  FDV_TRUST_PROXY: z
    .enum(['network', 'private', 'all', 'none'])
    .default('network')
    .describe(
      'Whose X-Forwarded-For to believe. "network" trusts the networks the ' +
        "API's own container is on — nginx and Caddy in the compose setup, " +
        'and nothing on your LAN; "private" trusts any private address (the ' +
        'old default); "all" is for a proxy elsewhere; "none" records the ' +
        'connecting address as it is.',
    ),
});

export type ApiConfig = z.infer<typeof schema>;

const withMasterKey = schema.refine((c) => c.FDV_MASTER_KEY || c.FDV_MASTER_KEY_FILE, {
  message: 'set FDV_MASTER_KEY (or FDV_MASTER_KEY_FILE); generate it with scripts/gen-env.mjs',
  path: ['FDV_MASTER_KEY'],
});

/**
 * An environment variable set to nothing is not set.
 *
 * Compose writes `FDV_RP_ID: ${FDV_RP_ID:-}` for anything optional, which
 * hands the container an empty string rather than leaving the variable
 * out. Without this, every optional setting would have to tolerate `''`
 * on its own, and the one that forgot would fail at startup with a
 * message about a field the self-hoster never set.
 */
function present(env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  return Object.fromEntries(Object.entries(env).filter(([, v]) => v !== ''));
}

export function loadConfig(env: NodeJS.ProcessEnv = process.env): ApiConfig {
  const parsed = withMasterKey.safeParse(present(env));
  if (!parsed.success) {
    const problems = parsed.error.issues
      .map((i) => `  ${i.path.join('.') || '(root)'}: ${i.message}`)
      .join('\n');
    throw new Error(`invalid configuration:\n${problems}`);
  }
  return parsed.data;
}
